### ISSUE TITLE
Processing of images other than square

### ISSUE THREAD

**Issue by au5tr1ng3r** [mahmoudnafifi/color-aware-style-transfer#1]
Hi, I am probably your first user. Haha.

Can one process images other than 1:1 aspect ratio?

**Comment by mahmoudnafifi** [comment]
Thanks for asking!

That should be ok, just change the transforms.Compose from [here](https://github.com/mahmoudnafifi/color-aware-style-transfer/blob/5f4d076dbeb3c23e1f80876082e1c637b908b875/color_aware_st.py#L784). But please note that it may affect the quality of style transfer.

**Comment by au5tr1ng3r** [comment]
Excellent, thanks for the very swift feedback
