### ISSUE TITLE
Questions about the mask

### ISSUE THREAD

**Issue by yanmingqiang** [mahmoudnafifi/color-aware-style-transfer#2]
Hello, when I read your article, I feel very innovative and have a strong interest, but I always have a question about how your mask is generated. Can you give me a detailed answer?

**Comment by mahmoudnafifi** [comment]
It is generated by weighting image pixels based on how close each pixel color is to one of the palette colors. Please check the [CreateMask class](https://github.com/mahmoudnafifi/color-aware-style-transfer/blob/e67f3b4420d4f04ca36f09a9713b31eef4f59c66/color_aware_st.py#L375) for more information.
